name: On dev branch push

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  sanity_check:
    name: Code checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check code quality and formatting
        run: pnpm run lint:check && pnpm run format:check

      - name: Check TS types
        run: pnpm run ts:check

      - name: Check build is fine
        run: pnpm run build

      - name: Run unit tests
        run: pnpm test

      - name: Run e2e tests
        run: pnpm cypress install && pnpm run e2e:run

      - name: Upload test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Cypress videos
          if-no-files-found: ignore
          path: cypress/videos/
