name: On Push

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install depdencies
        run: npm ci

      - name: Check code quality and formatting
        run: npm run lint:check && npm run format:check

      - name: Check TS types
        run: npm run ts:check

      - name: Run unit tests
        run: npm test

      - name: Run e2e tests
        run: npm run e2e:run

      - name: Run semantic release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
